# Generated by Django 5.1 on 2024-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
