# Generated by Django 5.1 on 2024-09-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
