# Generated by Django 5.1 on 2024-09-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
