# Generated by Django 5.1 on 2024-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0005_alter_products_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(to='productsite.category'),
        ),
    ]
