# Generated by Django 5.1 on 2024-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0006_remove_products_categories_products_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='productsite.category'),
        ),
    ]
