# Generated by Django 5.1 on 2024-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0007_alter_products_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productsite.category'),
        ),
    ]
