# Generated by Django 5.1 on 2024-09-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0008_remove_products_categories_products_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
