# Generated by Django 5.1 on 2024-09-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsite', '0009_rename_categories_products_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
